site_name: bqdp
site_url: https://bqdp.de/blog/
nav:
  - Home: index.md
  - Code: code.md
  - About: about.md
  - Programming:
      - git:
          - gitk as background process: programming/git/gitk_background_process.md
  - Linux:
      - Problems:
          - Firefox/Thunderbird starts very slowly: linux/problems/firefox_slow.md
  - Stuff:
    - TV Cabinet: stuff/tv_cabinet.md
extra_css:
  - assets/css/font.css
  - assets/css/swup.css
extra_javascript:
  - assets/js/3DViewer.min.js
theme:
  code:
    highlight_theme: material
  color_mode: dark
  features:
    - navigation.instant
    - content.code.copy
    - content.code.select
    - content.code.annotate
  font: false
  name: material
  palette:
    scheme: slate
  user_color_mode_toggle: true
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
